pages:
  image: node:lts
  stage: deploy
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm -F radiolise build-only
    - mv packages/radiolise/dist public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec
      gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
