services:
  express:
    restart: unless-stopped
    build:
      context: .
      args:
        - RADIOLISE_BUILD_TARGET
    init: true
    volumes:
      - site:/app/static

  caddy:
    restart: unless-stopped
    image: caddy:2
    environment:
      - RADIOLISE_SITE_ADDRESS
      - RADIOLISE_SERVER_OPTIONS
      - RADIOLISE_BACKEND_RULES
      - RADIOLISE_FRONTEND_RULES
    ports:
      - ${RADIOLISE_HTTP_PORT:-80}:80
      - ${RADIOLISE_HTTPS_PORT:-443}:443
      - ${RADIOLISE_HTTPS_PORT:-443}:443/udp
    depends_on:
      - express
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  site:
  caddy_data:
  caddy_config:
