services:
  express:
    restart: unless-stopped
    build:
      context: .
      dockerfile: build.Dockerfile
      target: build-${RADIOLISE_BUILD_TARGET:-fullstack}
    init: true
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    command: node packages/api/dist/server
    volumes:
      - site:/app/packages/radiolise/dist

  caddy:
    restart: unless-stopped
    image: caddy:2
    environment:
      - RADIOLISE_SITE_ADDRESS=${RADIOLISE_SITE_ADDRESS:-http://localhost}
      - RADIOLISE_SERVER_OPTIONS
      - RADIOLISE_BACKEND_RULES
      - RADIOLISE_FRONTEND_RULES
    ports:
      - ${RADIOLISE_HTTP_PORT:-80}:80
      - ${RADIOLISE_HTTPS_PORT:-443}:443
      - ${RADIOLISE_HTTPS_PORT:-443}:443/udp
      - 127.0.0.1:${RADIOLISE_SERVER_ADMIN_PORT:-2019}:2019
    depends_on:
      - express
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  site:
  caddy_data:
  caddy_config:
